### ISSUE TITLE
RPS2-STAMP Results Reproducibility

### ISSUE THREAD

**Issue by ilyes495** [YeoLab/Yeo_STAMP_Nature_Methods#6]
Hey thank you for sharing the code and the notebooks to generate plot and figures.

I tried to reproduce the results for the Ribo-STAMP experiments, but couldn't quite get similar results to the ones published in the paper. I obtained both the called edits results from the experiments below and also by running sailor pipeline on the raw data. I put the results in these slides for reference [here](https://docs.google.com/presentation/d/1S8cX6QbU78iqXVEkc5uhG0yo7g4wZGXS2Fu9RxZ1XsQ/edit?usp=sharing).

There are few questions I have:
1. It looks like samples _RPS2-STAMP-high-Torin 1_ and _RPS2-STAMP-Insulin 1_ are swapped (I used the data as it is from GEO website), _RPS2-STAMP-high-Torin 1_ has high edit number similar to _RPS2-STAMP-Insulin 2_. can you confirm that?
2. the called edits for _HEK293T-control-STAMP 72h high Torin-1 rep1_ sample (GSM4709491_Apobec_plusT_1_S30_L003_R1_001.fastqTr.sorted.STARUnmapped.out.sorted.STARAligned.out.sorted_a0_b0_e0.01.bed.gz) has high edit number similar to _HEK293T-RPS2-STAMP 48h high insulin rep2_, which is not what you would expect for a control sample, can you please clarify the issue here?
3. Only the 48 hours RPS2-STAMP samples are provided, but the paper uses the 72 hours samples, can these samples be shared as well?
4. you have used EPKM score to factor out the expression level of the gene when quantifying translation efficiency , but have you also considered the expression level of the construct (Protein-APOBEC)? there is a correlation between the expression level of the construct and the total edit number as shown in the slides linked above

Samples that I have looked at:
**Control:**
GSM4709491 | HEK293T-control-STAMP 72h high Torin-1 rep1
GSM4709492 | HEK293T-control-STAMP 72h high Torin-1 rep2
GSM4709493 | HEK293T-control-STAMP 72h high vehicle rep1
GSM4709494 | HEK293T-control-STAMP 72h high vehicle rep2

**RPS2-STAMP:**
GSM4709546 | HEK293T-RPS2-STAMP 48h high Torin-1 rep1
GSM4709547 | HEK293T-RPS2-STAMP 48h high Torin-1 rep2
GSM4709548 | HEK293T-RPS2-STAMP 48h high insulin rep1
GSM4709549 | HEK293T-RPS2-STAMP 48h high insulin rep2

**Comment by byee4** [comment]
Hi Ilyes, thanks for the work and apologies!

Not sure why the results don’t match up. I can take a look when I’m back in the office, but from a quick glance, there doesn’t seem to be a sample swap. I do remember each treatment was compared to the same timepoints, so perhaps there was a mistake during the upload to GEO. But I’ll need to look into that further as well.

From: Ilyes Baali ***@***.***>
Date: Tuesday, February 20, 2024 at 6:28 PM
To: YeoLab/Yeo_STAMP_Nature_Methods ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [YeoLab/Yeo_STAMP_Nature_Methods] RPS2-STAMP Results Reproducibility (Issue #6)

Hey thank you for sharing the code and the notebooks to generate plot and figures.

I tried to reproduce the results for the Ribo-STAMP experiments, but couldn't quite get similar results to the ones published in the paper. I obtained both the called edits results from the experiments below and also by running sailor pipeline on the raw data. I put the results in these slides for reference here<https://urldefense.com/v3/__https:/docs.google.com/presentation/d/1S8cX6QbU78iqXVEkc5uhG0yo7g4wZGXS2Fu9RxZ1XsQ/edit?usp=sharing__;!!LLK065n_VXAQ!iCd2O6hiUoVoKQd5TnASL28dTdxvD-kbOAhDXxyOwSRdsQTff51yau7NMrooaSWTu1IMezTGQlrkvidilBocB_XQkapK$>.

There are few questions I have:

  1.  It looks like samples RPS2-STAMP-high-Torin 1 and RPS2-STAMP-Insulin 1 are swapped (I used the data as it is from GEO website), RPS2-STAMP-high-Torin 1 has high edit number similar to RPS2-STAMP-Insulin 2. can you confirm that?
  2.  the called edits for HEK293T-control-STAMP 72h high Torin-1 rep1 sample (GSM4709491_Apobec_plusT_1_S30_L003_R1_001.fastqTr.sorted.STARUnmapped.out.sorted.STARAligned.out.sorted_a0_b0_e0.01.bed.gz) has high edit number similar to HEK293T-RPS2-STAMP 48h high insulin rep2, which is not what you would expect for a control sample, can you please clarify the issue here?
  3.  Only the 48 hours RPS2-STAMP samples are provided, but the paper uses the 72 hours samples, can these samples be shared as well?
  4.  you have used EPKM score to factor out the expression level of the gene when quantifying translation efficiency , but have you also considered the expression level of the construct (Protein-APOBEC)? there is a correlation between the expression level of the construct and the total edit number as shown in the slides linked above

Samples that I have looked at:
Control:
GSM4709491 | HEK293T-control-STAMP 72h high Torin-1 rep1
GSM4709492 | HEK293T-control-STAMP 72h high Torin-1 rep2
GSM4709493 | HEK293T-control-STAMP 72h high vehicle rep1
GSM4709494 | HEK293T-control-STAMP 72h high vehicle rep2

RPS2-STAMP:
GSM4709546 | HEK293T-RPS2-STAMP 48h high Torin-1 rep1
GSM4709547 | HEK293T-RPS2-STAMP 48h high Torin-1 rep2
GSM4709548 | HEK293T-RPS2-STAMP 48h high insulin rep1
GSM4709549 | HEK293T-RPS2-STAMP 48h high insulin rep2

**Comment by ilyes495** [comment]
Thank you for taking time to look at it! please let me know if you have any updates or need more information about how I obtained the results

Best,
Ilyes

**Comment by ilyes495** [comment]
Are there are any updates? Appreciate it!

**Comment by byee4** [comment]
Hi Ilyes, apologies as we’re going through a cluster migration at the moment and that’s taking up nearly all my time. However let me try and find the 72 hour files if they aren’t on GEO already.

From: Ilyes Baali ***@***.***>
Date: Thursday, March 7, 2024 at 7:11 AM
To: YeoLab/Yeo_STAMP_Nature_Methods ***@***.***>
Cc: Brian Yee ***@***.***>, Comment ***@***.***>
Subject: Re: [YeoLab/Yeo_STAMP_Nature_Methods] RPS2-STAMP Results Reproducibility (Issue #6)

Are there are any updates? Appreciate it!

**Comment by byee4** [comment]
Hi Ilyes, 

I tracked down the fastqs used for that figure and the genelist used. Once I can spare more time, I'll check GEO but for now they can be accessed with Globus:

[globus](https://app.globus.org/file-manager?origin_id=6bfaee95-e061-4ad8-a4ef-0e65ef4aabc8&origin_path=%2Fbay001%2F20200228_encore_kris%2F)

**Comment by ilyes495** [comment]
Thank you so much for sharing the fastqs. I was able to reproduce the results. The effect of the expression of the RPS2-APOBEC construct on the total edit number is not of a concern, as there was no clear correlation between the two.
